todo_list/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("web_app.urls", namespace="web_app"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web_app/urls.py
from django.urls import path

from web_app.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    ToggleTaskStatusView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="index"),
    path("add/", TaskCreateView.as_view(), name="add_task"),
    path("<int:pk>/edit/", TaskUpdateView.as_view(), name="edit_task"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="delete_task"),
    path(
        "<int:pk>/toggle/",
        ToggleTaskStatusView.as_view(),
        name="toggle_task_status"
    ),
    path("tags/", TagListView.as_view(), name="tags"),
    path("tags/add/", TagCreateView.as_view(), name="add_tag"),
    path("tags/<int:pk>/edit/", TagUpdateView.as_view(), name="edit_tag"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="delete_tag"),
]

app_name = "web_app"

web_app/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=63, unique=True)

    def __str__(self) -> str:
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag)

    class Meta:
        ordering = ["is_done", "-created_at"]

    def __str__(self) -> str:
        return self.content

web_app/forms.py
from django import forms
from .models import Task, Tag


class TaskForm(forms.ModelForm):
    deadline = forms.DateTimeField(
        input_formats=['%Y-%m-%d %H:%M'],
        widget=forms.DateTimeInput(attrs={
            'type': 'datetime-local',
            'class': 'form-control'
        }),
        required=False
    )
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Task
        fields = ['content', 'deadline', 'tags']

web_app/views.py
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic

from web_app.forms import TaskForm
from web_app.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    template_name = "web_app/index.html"
    context_object_name = "tasks"


class TaskCreateView(generic.CreateView):
    model = Task
    template_name = "web_app/add_task.html"
    form_class = TaskForm

    def get_success_url(self) -> HttpResponse:
        return reverse_lazy("web_app:index")


class TaskUpdateView(generic.UpdateView):
    model = Task
    template_name = "web_app/edit_task.html"
    form_class = TaskForm

    def get_success_url(self) -> HttpResponse:
        return reverse_lazy("web_app:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    template_name = "web_app/delete_task.html"

    def get_success_url(self) -> HttpResponse:
        return reverse_lazy("web_app:index")


class ToggleTaskStatusView(generic.View):
    def get(self, request, *args, **kwargs) -> HttpResponse:
        task = Task.objects.get(pk=kwargs["pk"])
        task.is_done = not task.is_done
        task.save()
        return redirect("web_app:index")


class TagListView(generic.ListView):
    model = Tag
    template_name = "web_app/tags.html"
    context_object_name = "tags"


class TagCreateView(generic.CreateView):
    model = Tag
    template_name = "web_app/add_tag.html"
    context_object_name = "tags"
    fields = ["name"]

    def get_success_url(self) -> HttpResponse:
        return reverse_lazy("web_app:tags")


class TagUpdateView(generic.UpdateView):
    model = Tag
    template_name = "web_app/edit_tag.html"
    fields = ["name"]

    def get_success_url(self) -> HttpResponse:
        return reverse_lazy("web_app:tags")


class TagDeleteView(generic.DeleteView):
    model = Tag
    template_name = "web_app/delete_tag.html"

    def get_success_url(self) -> HttpResponse:
        return reverse_lazy("web_app:tags")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ToDo List</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
        crossorigin="anonymous">
  <link href="{% static 'css/styles.css' %}" rel="stylesheet">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
                {% include "includes/navbar.html" %}
            {% endblock %}
        </div>
        <div class="col-sm-10 ">
            {% block content %}{% endblock %}
        </div>
    </div>
</div>
</body>

</html>

templates/includes/navbar.html
<ul class="sidebar-nav list-group">
    <li class="list-group-item"><a href="{% url 'web_app:index' %}">Home</a></li>
    <li class="list-group-item"><a href="{% url 'web_app:tags' %}">Tags</a></li>
</ul>

templates/web_app/add_tag.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container">
    <h2>Add New Tag</h2>
    <form method="post" action="">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-success">Add Tag</button>
      <a href="{% url 'web_app:tags' %}" class="btn btn-secondary">Cancel</a>
    </form>
  </div>
{% endblock %}

templates/web_app/add_task.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container" style="width: 600px">
    <form method="post" action="">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-success">Add Task</button>
      <a href="{% url 'web_app:index' %}" class="btn btn-secondary">Cancel</a>
    </form>
  </div>
{% endblock %}

templates/web_app/delete_tag.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <H2>Delete Tag</H2>

    <p>Are you sure want to delete the tag: <strong>{{ tag.name }}</strong> ?</p>
    <form action="" method="post">
      {% csrf_token %}
      <input type="submit" value="Yes, delete" class="btn btn-danger"/>
      <a href="{% url 'web_app:tags' %}" class="btn btn-secondary">Cancel</a>
    </form>
  </div>
{% endblock %}

templates/web_app/delete_task.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <H2>Delete Task</H2>

    <p>Are you sure want to delete the task: <strong>{{ task.content }}</strong> ?</p>
    <form action="" method="post">
      {% csrf_token %}
      <input type="submit" value="Yes, delete" class="btn btn-danger"/>
      <a href="{% url 'web_app:index' %}" class="btn btn-secondary">Cancel</a>
    </form>
  </div>
{% endblock %}

templates/web_app/edit_tag.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container" style="width: 600px">
    <h2>Update Tag</h2>
    <form action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary">Update Tag</button>
      <a href="{% url 'web_app:tags' %}" class="btn btn-secondary">Cancel</a>
    </form>
  </div>
{% endblock %}

templates/web_app/edit_task.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container" style="width: 600px">
    <h2>Update Task</h2>
    <form action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary">Update Task</button>
      <a href="{% url 'web_app:index' %}" class="btn btn-secondary">Cancel</a>
    </form>
  </div>
{% endblock %}

templates/web_app/index.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <h2>
      TODO list
      <a href="{% url 'web_app:add_task' %}" class="btn btn-primary" style="float: right">Add task</a>
    </h2><br>
  </div>
  {% for task in tasks %}
    <div class="container">
      <p>
        <strong>{{ task.content }}</strong>
        <span class="{% if task.is_done %}done{% else %}not-done{% endif %}">
                {{ task.is_done|yesno:"Done,Not done" }}
            </span>
      </p>
      {% if task.is_done %}
        <a href="{% url 'web_app:toggle_task_status' task.id %}" class="btn btn-secondary" style="float: right">Undo</a>
      {% else %}
        <a href="{% url 'web_app:toggle_task_status' task.id %}" class="btn btn-success"
           style="float: right">Complete</a>
      {% endif %}

      <p>Created: {{ task.created_at }}
        {% if task.deadline %}
          <span class="deadline"> Deadline: {{ task.deadline }}</span>
        {% endif %}
      </p>

      <p>Tags:
        {% for tag in task.tags.all %}
          {{ tag.name }}
        {% endfor %}
        <a href="{% url 'web_app:edit_task' task.id %}">Update</a>
        <a href="{% url 'web_app:delete_task' task.id %}">Delete</a>
      </p>
      <hr>
    </div>
  {% endfor %}
{% endblock %}

templates/web_app/tags.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <h2>Tags <a href="{% url 'web_app:add_tag' %}" style="float: right;" class="btn btn-primary">Add Tag</a></h2>
  </div>
  <div class="container">
    {% if tags %}
      <table class="table">
        <tr>
          <th>Name</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>
        {% for tag in tags %}
          <tr>
            <td>
              {{ tag.name }}
            </td>
            <td>
              <a href="{% url 'web_app:edit_tag' pk=tag.id %}" class="btn btn-secondary">Update</a>
            </td>
            <td>
              <a href="{% url 'web_app:delete_tag' pk=tag.id %}" class="btn btn-secondary">Delete</a>
            </td>
          </tr>
        {% endfor %}
      </table>
    {% endif %}
  </div>
{% endblock %}

templates/wep_app/tags.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <h2>Tags <a href="{% url 'web_app:add_tag' %}" style="float: right;" class="btn btn-primary">Add Tag</a></h2>
  </div>
  <div class="container">
    {% if tags %}
      <table class="table">
        <tr>
          <th>Name</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>
        {% for tag in tags %}
          <tr>
            <td>
              {{ tag.name }}
            </td>
            <td>
              <a href="{% url 'web_app:edit_tag' pk=tag.id %}" class="btn btn-secondary">Update</a>
            </td>
            <td>
              <a href="{% url 'web_app:delete_tag' pk=tag.id %}" class="btn btn-secondary">Delete</a>
            </td>
          </tr>
        {% endfor %}
      </table>

    {% endif %}
  </div>
{% endblock %}